name: .NET CI/CD on Self-Hosted Runner

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # 👈 runs on your local IIS machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # or your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy to IIS folder
        run: |
          Remove-Item -Recurse -Force "C:\inetpub\wwwroot\MyDotNetCIApp\*" -ErrorAction SilentlyContinue
          Copy-Item -Recurse -Force ./publish/* "C:\inetpub\wwwroot\MyDotNetCIApp\"
